version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: portalpro_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: portalpro
      MYSQL_USER: portalpro
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: portalpro_adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data:
